### ISSUE TITLE
ToDo for 1st release

### ISSUE THREAD

**Issue by AntonMrt** [valvals/devtools#52]
- [x] Finish custom settings for different types of plots
- [x] #68
- [x] #69 
- [x] #70
- [x] finish settings 
- [x] #77
- [x] #83 
- [x] #90 
- [x] #76 
- [x] update site
- [x] #67
- [ ] davis logo to html
- [x] licence text to h or cpp files
- [x] #114 
- [x] QT Gui
- [x] save position GUI to json
- [x] exe icon
- [x] multisize ico to exe
- [x] version to exe
- [x] make handling of _nan_ and _inf_ values in dv::show()
- [x] rename gui.exe to something else
- [ ] (optional) decrease resolution option for viewing matrix as Surface
- [ ] add deps user json deps  keys 
- [x] hold on / hold off
